namespace linkapprove
{
	public partial class SecondForm : global::System.Windows.Forms.Form
	{
		private global::System.ComponentModel.IContainer components;
		internal global::System.Windows.Forms.Timer approveTimer;
		internal global::System.Windows.Forms.PictureBox socialInstagram;
		internal global::System.Windows.Forms.PictureBox webHilebol;
		internal global::System.Windows.Forms.PictureBox ImageCSBOL;
		internal global::System.Windows.Forms.PictureBox socialYoutube;
		private global::System.Windows.Forms.Label linkLabel1;
		private global::System.Windows.Forms.Panel linkApprovePanel;
		private global::System.Windows.Forms.PictureBox linkIcon12;
		private global::System.Windows.Forms.Label linkLabel12;
		private global::System.Windows.Forms.PictureBox linkIcon9;
		private global::System.Windows.Forms.Label linkLabel9;
		private global::System.Windows.Forms.PictureBox linkIcon6;
		private global::System.Windows.Forms.Label linkLabel6;
		private global::System.Windows.Forms.PictureBox linkIcon3;
		private global::System.Windows.Forms.Label linkLabel3;
		private global::System.Windows.Forms.PictureBox linkIcon11;
		private global::System.Windows.Forms.Label linkLabel11;
		private global::System.Windows.Forms.PictureBox linkIcon8;
		private global::System.Windows.Forms.Label linkLabel8;
		private global::System.Windows.Forms.PictureBox linkIcon5;
		private global::System.Windows.Forms.Label linkLabel5;
		private global::System.Windows.Forms.PictureBox linkIcon2;
		private global::System.Windows.Forms.Label linkLabel2;
		private global::System.Windows.Forms.PictureBox linkIcon10;
		private global::System.Windows.Forms.Label linkLabel10;
		private global::System.Windows.Forms.PictureBox linkIcon7;
		private global::System.Windows.Forms.Label linkLabel7;
		private global::System.Windows.Forms.PictureBox linkIcon4;
		private global::System.Windows.Forms.Label linkLabel4;
		private global::System.Windows.Forms.PictureBox linkIcon1;
		internal global::System.Windows.Forms.PictureBox ImageLoading;
		private global::System.Windows.Forms.Panel altPanel;
		private global::System.Windows.Forms.Timer flow;
		private global::System.Windows.Forms.Panel panel3;
		private global::System.Windows.Forms.PictureBox menuLicense;
		private global::System.Windows.Forms.PictureBox menuLink;
		private global::System.Windows.Forms.Timer HBIDCopiedFixer;
		private global::System.Windows.Forms.PictureBox licenseCodeTextboxBackground;
		private global::System.Windows.Forms.Label premiumRemainingTimeLeft;
		private global::System.Windows.Forms.Label liceneCodeEnterTextboxLeft;
		private global::System.Windows.Forms.Label licenseMessageLeft;
		private global::System.Windows.Forms.TextBox licenseCodeTextbox;
		private global::System.Windows.Forms.Label licenseCodeEnterButton;
		private global::System.Windows.Forms.Label hideLicenseMessageButton;
		private global::System.Windows.Forms.Panel licensePanel;
		private global::System.Windows.Forms.Panel linkApproveYoPanel;
		private global::System.Windows.Forms.PictureBox pictureBox1;
		private global::System.Windows.Forms.PictureBox menuLanguage;
		private global::System.Windows.Forms.Panel languagePanel;
		internal global::System.Windows.Forms.PictureBox bayrak_lt;
		internal global::System.Windows.Forms.PictureBox bayrak_cz;
		internal global::System.Windows.Forms.PictureBox bayrak_de;
		internal global::System.Windows.Forms.PictureBox bayrak_hu;
		internal global::System.Windows.Forms.PictureBox bayrak_eg;
		internal global::System.Windows.Forms.PictureBox bayrak_fr;
		internal global::System.Windows.Forms.PictureBox bayrak_es;
		internal global::System.Windows.Forms.PictureBox bayrak_ro;
		internal global::System.Windows.Forms.PictureBox bayrak_bg;
		internal global::System.Windows.Forms.PictureBox bayrak_br;
		internal global::System.Windows.Forms.PictureBox bayrak_pl;
		internal global::System.Windows.Forms.PictureBox bayrak_ru;
		internal global::System.Windows.Forms.PictureBox bayrak_tr;
		internal global::System.Windows.Forms.PictureBox bayrak_en;
		private global::System.Windows.Forms.Label languageLabel;
		public global::System.Windows.Forms.Label onayPeriyoduLabel;
		public global::System.Windows.Forms.Label ustteTutButton;
		public global::System.Windows.Forms.Label linkOnayiNasilYapilirButton;
		public global::System.Windows.Forms.Label son24SaatLabel;
		public global::System.Windows.Forms.Label licenseCodeEnterLabel;
		public global::System.Windows.Forms.Label buyLicenseButton;
		public global::System.Windows.Forms.Label copyHBIDButton;
		public global::System.Windows.Forms.Label premiumInfoLabel;
		public global::System.Windows.Forms.Label premiumRemainingTime;
		public global::System.Windows.Forms.Label licenseMessage;
		public global::System.Windows.Forms.Label languageContentLabel;
		public global::System.Windows.Forms.Label tebriklerLabel;
		private global::System.Windows.Forms.Button button1;
		
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::linkapprove.SecondForm));
			this.approveTimer = new global::System.Windows.Forms.Timer(this.components);
			this.linkLabel1 = new global::System.Windows.Forms.Label();
			this.linkApprovePanel = new global::System.Windows.Forms.Panel();
			this.ustteTutButton = new global::System.Windows.Forms.Label();
			this.linkOnayiNasilYapilirButton = new global::System.Windows.Forms.Label();
			this.onayPeriyoduLabel = new global::System.Windows.Forms.Label();
			this.linkIcon12 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel12 = new global::System.Windows.Forms.Label();
			this.linkIcon9 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel9 = new global::System.Windows.Forms.Label();
			this.linkIcon6 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel6 = new global::System.Windows.Forms.Label();
			this.linkIcon3 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel3 = new global::System.Windows.Forms.Label();
			this.linkIcon11 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel11 = new global::System.Windows.Forms.Label();
			this.linkIcon8 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel8 = new global::System.Windows.Forms.Label();
			this.linkIcon5 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel5 = new global::System.Windows.Forms.Label();
			this.linkIcon2 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel2 = new global::System.Windows.Forms.Label();
			this.linkIcon10 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel10 = new global::System.Windows.Forms.Label();
			this.linkIcon7 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel7 = new global::System.Windows.Forms.Label();
			this.linkIcon4 = new global::System.Windows.Forms.PictureBox();
			this.linkLabel4 = new global::System.Windows.Forms.Label();
			this.linkIcon1 = new global::System.Windows.Forms.PictureBox();
			this.son24SaatLabel = new global::System.Windows.Forms.Label();
			this.altPanel = new global::System.Windows.Forms.Panel();
			this.webHilebol = new global::System.Windows.Forms.PictureBox();
			this.socialInstagram = new global::System.Windows.Forms.PictureBox();
			this.socialYoutube = new global::System.Windows.Forms.PictureBox();
			this.flow = new global::System.Windows.Forms.Timer(this.components);
			this.panel3 = new global::System.Windows.Forms.Panel();
			this.menuLanguage = new global::System.Windows.Forms.PictureBox();
			this.menuLicense = new global::System.Windows.Forms.PictureBox();
			this.menuLink = new global::System.Windows.Forms.PictureBox();
			this.HBIDCopiedFixer = new global::System.Windows.Forms.Timer(this.components);
			this.licenseCodeEnterLabel = new global::System.Windows.Forms.Label();
			this.buyLicenseButton = new global::System.Windows.Forms.Label();
			this.copyHBIDButton = new global::System.Windows.Forms.Label();
			this.premiumInfoLabel = new global::System.Windows.Forms.Label();
			this.premiumRemainingTimeLeft = new global::System.Windows.Forms.Label();
			this.premiumRemainingTime = new global::System.Windows.Forms.Label();
			this.liceneCodeEnterTextboxLeft = new global::System.Windows.Forms.Label();
			this.licenseMessageLeft = new global::System.Windows.Forms.Label();
			this.licenseMessage = new global::System.Windows.Forms.Label();
			this.licenseCodeTextbox = new global::System.Windows.Forms.TextBox();
			this.hideLicenseMessageButton = new global::System.Windows.Forms.Label();
			this.licensePanel = new global::System.Windows.Forms.Panel();
			this.licenseCodeEnterButton = new global::System.Windows.Forms.Label();
			this.licenseCodeTextboxBackground = new global::System.Windows.Forms.PictureBox();
			this.linkApproveYoPanel = new global::System.Windows.Forms.Panel();
			this.pictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.tebriklerLabel = new global::System.Windows.Forms.Label();
			this.languagePanel = new global::System.Windows.Forms.Panel();
			this.languageContentLabel = new global::System.Windows.Forms.Label();
			this.languageLabel = new global::System.Windows.Forms.Label();
			this.bayrak_lt = new global::System.Windows.Forms.PictureBox();
			this.bayrak_cz = new global::System.Windows.Forms.PictureBox();
			this.bayrak_de = new global::System.Windows.Forms.PictureBox();
			this.bayrak_hu = new global::System.Windows.Forms.PictureBox();
			this.bayrak_eg = new global::System.Windows.Forms.PictureBox();
			this.bayrak_fr = new global::System.Windows.Forms.PictureBox();
			this.bayrak_es = new global::System.Windows.Forms.PictureBox();
			this.bayrak_ro = new global::System.Windows.Forms.PictureBox();
			this.bayrak_bg = new global::System.Windows.Forms.PictureBox();
			this.bayrak_br = new global::System.Windows.Forms.PictureBox();
			this.bayrak_pl = new global::System.Windows.Forms.PictureBox();
			this.bayrak_ru = new global::System.Windows.Forms.PictureBox();
			this.bayrak_tr = new global::System.Windows.Forms.PictureBox();
			this.bayrak_en = new global::System.Windows.Forms.PictureBox();
			this.ImageCSBOL = new global::System.Windows.Forms.PictureBox();
			this.ImageLoading = new global::System.Windows.Forms.PictureBox();
			this.button1 = new global::System.Windows.Forms.Button();
			this.linkApprovePanel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon12).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon9).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon6).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon3).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon11).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon8).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon5).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon10).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon7).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon4).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon1).BeginInit();
			this.altPanel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.webHilebol).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.socialInstagram).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.socialYoutube).BeginInit();
			this.panel3.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.menuLanguage).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.menuLicense).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.menuLink).BeginInit();
			this.licensePanel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.licenseCodeTextboxBackground).BeginInit();
			this.linkApproveYoPanel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pictureBox1).BeginInit();
			this.languagePanel.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_lt).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_cz).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_de).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_hu).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_eg).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_fr).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_es).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_ro).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_bg).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_br).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_pl).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_ru).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_tr).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_en).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.ImageCSBOL).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.ImageLoading).BeginInit();
			base.SuspendLayout();
			this.approveTimer.Interval = 3000;
			this.approveTimer.Tick += new global::System.EventHandler(this.ApproveTimer_Tick);
			this.linkLabel1.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel1.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel1.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel1.Location = new global::System.Drawing.Point(2, 2);
			this.linkLabel1.Name = "linkLabel1";
			this.linkLabel1.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel1.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel1.TabIndex = 0;
			this.linkLabel1.Text = "LINK A";
			this.linkLabel1.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkApprovePanel.Controls.Add(this.ustteTutButton);
			this.linkApprovePanel.Controls.Add(this.linkOnayiNasilYapilirButton);
			this.linkApprovePanel.Controls.Add(this.onayPeriyoduLabel);
			this.linkApprovePanel.Controls.Add(this.linkIcon12);
			this.linkApprovePanel.Controls.Add(this.linkLabel12);
			this.linkApprovePanel.Controls.Add(this.linkIcon9);
			this.linkApprovePanel.Controls.Add(this.linkLabel9);
			this.linkApprovePanel.Controls.Add(this.linkIcon6);
			this.linkApprovePanel.Controls.Add(this.linkLabel6);
			this.linkApprovePanel.Controls.Add(this.linkIcon3);
			this.linkApprovePanel.Controls.Add(this.linkLabel3);
			this.linkApprovePanel.Controls.Add(this.linkIcon11);
			this.linkApprovePanel.Controls.Add(this.linkLabel11);
			this.linkApprovePanel.Controls.Add(this.linkIcon8);
			this.linkApprovePanel.Controls.Add(this.linkLabel8);
			this.linkApprovePanel.Controls.Add(this.linkIcon5);
			this.linkApprovePanel.Controls.Add(this.linkLabel5);
			this.linkApprovePanel.Controls.Add(this.linkIcon2);
			this.linkApprovePanel.Controls.Add(this.linkLabel2);
			this.linkApprovePanel.Controls.Add(this.linkIcon10);
			this.linkApprovePanel.Controls.Add(this.linkLabel10);
			this.linkApprovePanel.Controls.Add(this.linkIcon7);
			this.linkApprovePanel.Controls.Add(this.linkLabel7);
			this.linkApprovePanel.Controls.Add(this.linkIcon4);
			this.linkApprovePanel.Controls.Add(this.linkLabel4);
			this.linkApprovePanel.Controls.Add(this.linkIcon1);
			this.linkApprovePanel.Controls.Add(this.linkLabel1);
			this.linkApprovePanel.Location = new global::System.Drawing.Point(429, 166);
			this.linkApprovePanel.Name = "linkApprovePanel";
			this.linkApprovePanel.Size = new global::System.Drawing.Size(359, 227);
			this.linkApprovePanel.TabIndex = 101;
			this.linkApprovePanel.Visible = false;
			this.ustteTutButton.BackColor = global::System.Drawing.Color.FromArgb(241, 242, 246);
			this.ustteTutButton.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.ustteTutButton.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.ustteTutButton.ForeColor = global::System.Drawing.Color.FromArgb(28, 117, 239);
			this.ustteTutButton.Location = new global::System.Drawing.Point(235, 197);
			this.ustteTutButton.Name = "ustteTutButton";
			this.ustteTutButton.Padding = new global::System.Windows.Forms.Padding(5);
			this.ustteTutButton.Size = new global::System.Drawing.Size(123, 28);
			this.ustteTutButton.TabIndex = 29;
			this.ustteTutButton.Text = "Üstte Tut";
			this.ustteTutButton.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.ustteTutButton.Click += new global::System.EventHandler(this.ustteTutButton_Click);
			this.ustteTutButton.MouseEnter += new global::System.EventHandler(this.ustteTutButton_MouseEnter);
			this.ustteTutButton.MouseLeave += new global::System.EventHandler(this.ustteTutButton_MouseLeave);
			this.linkOnayiNasilYapilirButton.BackColor = global::System.Drawing.Color.FromArgb(28, 117, 239);
			this.linkOnayiNasilYapilirButton.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkOnayiNasilYapilirButton.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkOnayiNasilYapilirButton.ForeColor = global::System.Drawing.Color.White;
			this.linkOnayiNasilYapilirButton.Location = new global::System.Drawing.Point(1, 197);
			this.linkOnayiNasilYapilirButton.Name = "linkOnayiNasilYapilirButton";
			this.linkOnayiNasilYapilirButton.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkOnayiNasilYapilirButton.Size = new global::System.Drawing.Size(228, 28);
			this.linkOnayiNasilYapilirButton.TabIndex = 28;
			this.linkOnayiNasilYapilirButton.Text = "Link onayı nasıl yapılır? [▶️]";
			this.linkOnayiNasilYapilirButton.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkOnayiNasilYapilirButton.Click += new global::System.EventHandler(this.linkOnayiNasilYapilirButton_Click);
			this.linkOnayiNasilYapilirButton.MouseEnter += new global::System.EventHandler(this.linkOnayiNasilYapilirButton_MouseEnter);
			this.linkOnayiNasilYapilirButton.MouseLeave += new global::System.EventHandler(this.linkOnayiNasilYapilirButton_MouseLeave);
			this.onayPeriyoduLabel.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.onayPeriyoduLabel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.onayPeriyoduLabel.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.onayPeriyoduLabel.Location = new global::System.Drawing.Point(1, 140);
			this.onayPeriyoduLabel.Name = "onayPeriyoduLabel";
			this.onayPeriyoduLabel.Padding = new global::System.Windows.Forms.Padding(5);
			this.onayPeriyoduLabel.Size = new global::System.Drawing.Size(357, 42);
			this.onayPeriyoduLabel.TabIndex = 26;
			this.onayPeriyoduLabel.Text = "Onay için 8 adet link geçişi yapmalısınız.\r\nOnay periyodu 24 saattir.";
			this.onayPeriyoduLabel.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon12.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon12.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon12.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("linkIcon12.Image");
			this.linkIcon12.Location = new global::System.Drawing.Point(328, 98);
			this.linkIcon12.Name = "linkIcon12";
			this.linkIcon12.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon12.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon12.TabIndex = 23;
			this.linkIcon12.TabStop = false;
			this.linkIcon12.Click += new global::System.EventHandler(this.linkIcon12_Click);
			this.linkLabel12.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel12.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel12.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel12.Location = new global::System.Drawing.Point(259, 98);
			this.linkLabel12.Name = "linkLabel12";
			this.linkLabel12.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel12.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel12.TabIndex = 22;
			this.linkLabel12.Text = "LINK A";
			this.linkLabel12.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon9.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon9.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon9.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("linkIcon9.Image");
			this.linkIcon9.Location = new global::System.Drawing.Point(328, 66);
			this.linkIcon9.Name = "linkIcon9";
			this.linkIcon9.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon9.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon9.TabIndex = 21;
			this.linkIcon9.TabStop = false;
			this.linkIcon9.Click += new global::System.EventHandler(this.linkIcon9_Click);
			this.linkLabel9.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel9.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel9.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel9.Location = new global::System.Drawing.Point(259, 66);
			this.linkLabel9.Name = "linkLabel9";
			this.linkLabel9.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel9.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel9.TabIndex = 20;
			this.linkLabel9.Text = "LINK A";
			this.linkLabel9.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon6.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon6.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon6.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("linkIcon6.Image");
			this.linkIcon6.Location = new global::System.Drawing.Point(328, 34);
			this.linkIcon6.Name = "linkIcon6";
			this.linkIcon6.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon6.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon6.TabIndex = 19;
			this.linkIcon6.TabStop = false;
			this.linkIcon6.Click += new global::System.EventHandler(this.linkIcon6_Click);
			this.linkLabel6.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel6.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel6.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel6.Location = new global::System.Drawing.Point(259, 34);
			this.linkLabel6.Name = "linkLabel6";
			this.linkLabel6.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel6.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel6.TabIndex = 18;
			this.linkLabel6.Text = "LINK A";
			this.linkLabel6.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon3.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon3.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon3.Image = global::linkapprove.Properties.Resources.link_open;
			this.linkIcon3.Location = new global::System.Drawing.Point(328, 2);
			this.linkIcon3.Name = "linkIcon3";
			this.linkIcon3.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon3.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon3.TabIndex = 17;
			this.linkIcon3.TabStop = false;
			this.linkIcon3.Click += new global::System.EventHandler(this.linkIcon3_Click);
			this.linkLabel3.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel3.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel3.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel3.Location = new global::System.Drawing.Point(259, 2);
			this.linkLabel3.Name = "linkLabel3";
			this.linkLabel3.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel3.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel3.TabIndex = 16;
			this.linkLabel3.Text = "LINK A";
			this.linkLabel3.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon11.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon11.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon11.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("linkIcon11.Image");
			this.linkIcon11.Location = new global::System.Drawing.Point(199, 98);
			this.linkIcon11.Name = "linkIcon11";
			this.linkIcon11.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon11.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon11.TabIndex = 15;
			this.linkIcon11.TabStop = false;
			this.linkIcon11.Click += new global::System.EventHandler(this.linkIcon11_Click);
			this.linkLabel11.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel11.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel11.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel11.Location = new global::System.Drawing.Point(130, 98);
			this.linkLabel11.Name = "linkLabel11";
			this.linkLabel11.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel11.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel11.TabIndex = 14;
			this.linkLabel11.Text = "LINK A";
			this.linkLabel11.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon8.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon8.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon8.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("linkIcon8.Image");
			this.linkIcon8.Location = new global::System.Drawing.Point(199, 66);
			this.linkIcon8.Name = "linkIcon8";
			this.linkIcon8.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon8.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon8.TabIndex = 13;
			this.linkIcon8.TabStop = false;
			this.linkIcon8.Click += new global::System.EventHandler(this.linkIcon8_Click);
			this.linkLabel8.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel8.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel8.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel8.Location = new global::System.Drawing.Point(130, 66);
			this.linkLabel8.Name = "linkLabel8";
			this.linkLabel8.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel8.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel8.TabIndex = 12;
			this.linkLabel8.Text = "LINK A";
			this.linkLabel8.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon5.BackColor = global::System.Drawing.Color.FromArgb(241, 242, 246);
			this.linkIcon5.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon5.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("linkIcon5.Image");
			this.linkIcon5.Location = new global::System.Drawing.Point(199, 34);
			this.linkIcon5.Name = "linkIcon5";
			this.linkIcon5.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon5.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon5.TabIndex = 11;
			this.linkIcon5.TabStop = false;
			this.linkIcon5.Click += new global::System.EventHandler(this.linkIcon5_Click);
			this.linkLabel5.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel5.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel5.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel5.Location = new global::System.Drawing.Point(130, 34);
			this.linkLabel5.Name = "linkLabel5";
			this.linkLabel5.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel5.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel5.TabIndex = 10;
			this.linkLabel5.Text = "LINK A";
			this.linkLabel5.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon2.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon2.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon2.Image = global::linkapprove.Properties.Resources.link_open;
			this.linkIcon2.Location = new global::System.Drawing.Point(199, 2);
			this.linkIcon2.Name = "linkIcon2";
			this.linkIcon2.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon2.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon2.TabIndex = 9;
			this.linkIcon2.TabStop = false;
			this.linkIcon2.Click += new global::System.EventHandler(this.linkIcon2_Click);
			this.linkLabel2.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel2.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel2.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel2.Location = new global::System.Drawing.Point(130, 2);
			this.linkLabel2.Name = "linkLabel2";
			this.linkLabel2.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel2.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel2.TabIndex = 8;
			this.linkLabel2.Text = "LINK A";
			this.linkLabel2.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon10.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon10.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon10.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("linkIcon10.Image");
			this.linkIcon10.Location = new global::System.Drawing.Point(71, 98);
			this.linkIcon10.Name = "linkIcon10";
			this.linkIcon10.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon10.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon10.TabIndex = 7;
			this.linkIcon10.TabStop = false;
			this.linkIcon10.Click += new global::System.EventHandler(this.linkIcon10_Click);
			this.linkLabel10.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel10.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel10.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel10.Location = new global::System.Drawing.Point(2, 98);
			this.linkLabel10.Name = "linkLabel10";
			this.linkLabel10.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel10.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel10.TabIndex = 6;
			this.linkLabel10.Text = "LINK A";
			this.linkLabel10.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon7.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon7.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon7.Image = (global::System.Drawing.Image)componentResourceManager.GetObject("linkIcon7.Image");
			this.linkIcon7.Location = new global::System.Drawing.Point(71, 66);
			this.linkIcon7.Name = "linkIcon7";
			this.linkIcon7.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon7.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon7.TabIndex = 5;
			this.linkIcon7.TabStop = false;
			this.linkIcon7.Click += new global::System.EventHandler(this.linkIcon7_Click);
			this.linkLabel7.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel7.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel7.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel7.Location = new global::System.Drawing.Point(2, 66);
			this.linkLabel7.Name = "linkLabel7";
			this.linkLabel7.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel7.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel7.TabIndex = 4;
			this.linkLabel7.Text = "LINK A";
			this.linkLabel7.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon4.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon4.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon4.Image = global::linkapprove.Properties.Resources.link_open;
			this.linkIcon4.Location = new global::System.Drawing.Point(71, 34);
			this.linkIcon4.Name = "linkIcon4";
			this.linkIcon4.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon4.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon4.TabIndex = 3;
			this.linkIcon4.TabStop = false;
			this.linkIcon4.Click += new global::System.EventHandler(this.linkIcon4_Click);
			this.linkLabel4.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.linkLabel4.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.linkLabel4.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.linkLabel4.Location = new global::System.Drawing.Point(2, 34);
			this.linkLabel4.Name = "linkLabel4";
			this.linkLabel4.Padding = new global::System.Windows.Forms.Padding(5);
			this.linkLabel4.Size = new global::System.Drawing.Size(69, 28);
			this.linkLabel4.TabIndex = 2;
			this.linkLabel4.Text = "LINK A";
			this.linkLabel4.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.linkIcon1.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.linkIcon1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.linkIcon1.Image = global::linkapprove.Properties.Resources.link_open;
			this.linkIcon1.Location = new global::System.Drawing.Point(71, 2);
			this.linkIcon1.Name = "linkIcon1";
			this.linkIcon1.Size = new global::System.Drawing.Size(30, 28);
			this.linkIcon1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.linkIcon1.TabIndex = 1;
			this.linkIcon1.TabStop = false;
			this.linkIcon1.Click += new global::System.EventHandler(this.linkIcon1_Click);
			this.son24SaatLabel.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.son24SaatLabel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.son24SaatLabel.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.son24SaatLabel.Location = new global::System.Drawing.Point(1, 69);
			this.son24SaatLabel.Name = "son24SaatLabel";
			this.son24SaatLabel.Padding = new global::System.Windows.Forms.Padding(5);
			this.son24SaatLabel.Size = new global::System.Drawing.Size(357, 28);
			this.son24SaatLabel.TabIndex = 30;
			this.son24SaatLabel.Text = "Son 24 saatte, seninle beraber {0} kişi buradaydı.";
			this.son24SaatLabel.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.altPanel.Controls.Add(this.webHilebol);
			this.altPanel.Controls.Add(this.socialInstagram);
			this.altPanel.Controls.Add(this.son24SaatLabel);
			this.altPanel.Controls.Add(this.socialYoutube);
			this.altPanel.Location = new global::System.Drawing.Point(45, 437);
			this.altPanel.Name = "altPanel";
			this.altPanel.Size = new global::System.Drawing.Size(359, 99);
			this.altPanel.TabIndex = 104;
			this.altPanel.Visible = false;
			this.webHilebol.BackColor = global::System.Drawing.Color.Transparent;
			this.webHilebol.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.webHilebol.Image = global::linkapprove.Properties.Resources.mini__;
			this.webHilebol.Location = new global::System.Drawing.Point(152, 1);
			this.webHilebol.Name = "webHilebol";
			this.webHilebol.Size = new global::System.Drawing.Size(56, 41);
			this.webHilebol.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.webHilebol.TabIndex = 95;
			this.webHilebol.TabStop = false;
			this.webHilebol.Click += new global::System.EventHandler(this.ImageHilebol_Click);
			this.socialInstagram.BackColor = global::System.Drawing.Color.Transparent;
			this.socialInstagram.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.socialInstagram.Image = global::linkapprove.Properties.Resources.instagram;
			this.socialInstagram.Location = new global::System.Drawing.Point(324, 5);
			this.socialInstagram.Name = "socialInstagram";
			this.socialInstagram.Size = new global::System.Drawing.Size(32, 32);
			this.socialInstagram.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.socialInstagram.TabIndex = 93;
			this.socialInstagram.TabStop = false;
			this.socialInstagram.Click += new global::System.EventHandler(this.ImageInstagram_Click);
			this.socialYoutube.BackColor = global::System.Drawing.Color.Transparent;
			this.socialYoutube.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.socialYoutube.Image = global::linkapprove.Properties.Resources.youtube__2_2;
			this.socialYoutube.Location = new global::System.Drawing.Point(1, 5);
			this.socialYoutube.Name = "socialYoutube";
			this.socialYoutube.Size = new global::System.Drawing.Size(32, 32);
			this.socialYoutube.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.socialYoutube.TabIndex = 94;
			this.socialYoutube.TabStop = false;
			this.socialYoutube.Click += new global::System.EventHandler(this.ImageYoutube_Click);
			this.flow.Interval = 1;
			this.flow.Tick += new global::System.EventHandler(this.firstTimer_Tick);
			this.panel3.Controls.Add(this.menuLanguage);
			this.panel3.Controls.Add(this.menuLicense);
			this.panel3.Controls.Add(this.menuLink);
			this.panel3.Location = new global::System.Drawing.Point(45, 159);
			this.panel3.Name = "panel3";
			this.panel3.Size = new global::System.Drawing.Size(359, 38);
			this.panel3.TabIndex = 106;
			this.menuLanguage.BackColor = global::System.Drawing.Color.White;
			this.menuLanguage.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.menuLanguage.Image = global::linkapprove.Properties.Resources.m_translate_0;
			this.menuLanguage.Location = new global::System.Drawing.Point(204, 1);
			this.menuLanguage.Name = "menuLanguage";
			this.menuLanguage.Size = new global::System.Drawing.Size(36, 36);
			this.menuLanguage.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.menuLanguage.TabIndex = 30;
			this.menuLanguage.TabStop = false;
			this.menuLanguage.Click += new global::System.EventHandler(this.menuLanguage_Click);
			this.menuLicense.BackColor = global::System.Drawing.Color.White;
			this.menuLicense.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.menuLicense.Image = global::linkapprove.Properties.Resources.m_key_0;
			this.menuLicense.Location = new global::System.Drawing.Point(162, 1);
			this.menuLicense.Name = "menuLicense";
			this.menuLicense.Size = new global::System.Drawing.Size(36, 36);
			this.menuLicense.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.menuLicense.TabIndex = 29;
			this.menuLicense.TabStop = false;
			this.menuLicense.Click += new global::System.EventHandler(this.menuLicense_Click);
			this.menuLink.BackColor = global::System.Drawing.Color.White;
			this.menuLink.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.menuLink.Image = global::linkapprove.Properties.Resources.m_link_0;
			this.menuLink.Location = new global::System.Drawing.Point(120, 1);
			this.menuLink.Name = "menuLink";
			this.menuLink.Size = new global::System.Drawing.Size(36, 36);
			this.menuLink.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.menuLink.TabIndex = 28;
			this.menuLink.TabStop = false;
			this.menuLink.Click += new global::System.EventHandler(this.menuLink_Click);
			this.HBIDCopiedFixer.Interval = 3000;
			this.HBIDCopiedFixer.Tick += new global::System.EventHandler(this.HBIDCopiedFixer_Tick);
			this.licenseCodeEnterLabel.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.licenseCodeEnterLabel.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.licenseCodeEnterLabel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f);
			this.licenseCodeEnterLabel.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.licenseCodeEnterLabel.Location = new global::System.Drawing.Point(1, 1);
			this.licenseCodeEnterLabel.Name = "licenseCodeEnterLabel";
			this.licenseCodeEnterLabel.Padding = new global::System.Windows.Forms.Padding(5);
			this.licenseCodeEnterLabel.Size = new global::System.Drawing.Size(144, 27);
			this.licenseCodeEnterLabel.TabIndex = 6;
			this.licenseCodeEnterLabel.Text = "Lisans Kodu Kullan";
			this.licenseCodeEnterLabel.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.buyLicenseButton.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.buyLicenseButton.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.buyLicenseButton.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.buyLicenseButton.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.buyLicenseButton.Location = new global::System.Drawing.Point(1, 197);
			this.buyLicenseButton.Name = "buyLicenseButton";
			this.buyLicenseButton.Padding = new global::System.Windows.Forms.Padding(5);
			this.buyLicenseButton.Size = new global::System.Drawing.Size(174, 28);
			this.buyLicenseButton.TabIndex = 29;
			this.buyLicenseButton.Text = "Lisans Satın Al";
			this.buyLicenseButton.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.buyLicenseButton.Click += new global::System.EventHandler(this.buyLicenseButton_Click);
			this.buyLicenseButton.MouseEnter += new global::System.EventHandler(this.buyLicenseButton_MouseEnter);
			this.buyLicenseButton.MouseLeave += new global::System.EventHandler(this.buyLicenseButton_MouseLeave);
			this.copyHBIDButton.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.copyHBIDButton.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.copyHBIDButton.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.copyHBIDButton.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.copyHBIDButton.Location = new global::System.Drawing.Point(184, 197);
			this.copyHBIDButton.Name = "copyHBIDButton";
			this.copyHBIDButton.Padding = new global::System.Windows.Forms.Padding(5);
			this.copyHBIDButton.Size = new global::System.Drawing.Size(174, 28);
			this.copyHBIDButton.TabIndex = 30;
			this.copyHBIDButton.Text = "HBID Kopyala";
			this.copyHBIDButton.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.copyHBIDButton.Click += new global::System.EventHandler(this.copyHBIDButton_Click);
			this.copyHBIDButton.MouseEnter += new global::System.EventHandler(this.copyHBIDButton_MouseEnter);
			this.copyHBIDButton.MouseLeave += new global::System.EventHandler(this.copyHBIDButton_MouseLeave);
			this.premiumInfoLabel.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.premiumInfoLabel.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.premiumInfoLabel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f);
			this.premiumInfoLabel.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.premiumInfoLabel.Location = new global::System.Drawing.Point(1, 118);
			this.premiumInfoLabel.Name = "premiumInfoLabel";
			this.premiumInfoLabel.Padding = new global::System.Windows.Forms.Padding(5);
			this.premiumInfoLabel.Size = new global::System.Drawing.Size(112, 27);
			this.premiumInfoLabel.TabIndex = 37;
			this.premiumInfoLabel.Text = "Premium Bilgi";
			this.premiumInfoLabel.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.premiumRemainingTimeLeft.BackColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.premiumRemainingTimeLeft.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.premiumRemainingTimeLeft.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.premiumRemainingTimeLeft.ForeColor = global::System.Drawing.Color.White;
			this.premiumRemainingTimeLeft.Location = new global::System.Drawing.Point(1, 150);
			this.premiumRemainingTimeLeft.Name = "premiumRemainingTimeLeft";
			this.premiumRemainingTimeLeft.Padding = new global::System.Windows.Forms.Padding(5);
			this.premiumRemainingTimeLeft.Size = new global::System.Drawing.Size(77, 28);
			this.premiumRemainingTimeLeft.TabIndex = 39;
			this.premiumRemainingTimeLeft.Text = "Kalan süre: {0} gün, {0} saat, {0} dakika.";
			this.premiumRemainingTimeLeft.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.premiumRemainingTime.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.premiumRemainingTime.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.premiumRemainingTime.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.premiumRemainingTime.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.premiumRemainingTime.Location = new global::System.Drawing.Point(5, 150);
			this.premiumRemainingTime.Name = "premiumRemainingTime";
			this.premiumRemainingTime.Padding = new global::System.Windows.Forms.Padding(5);
			this.premiumRemainingTime.Size = new global::System.Drawing.Size(352, 28);
			this.premiumRemainingTime.TabIndex = 38;
			this.premiumRemainingTime.Text = "Kalan süre: {0} gün, {0} saat, {0} dakika.";
			this.premiumRemainingTime.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.liceneCodeEnterTextboxLeft.BackColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.liceneCodeEnterTextboxLeft.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.liceneCodeEnterTextboxLeft.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.liceneCodeEnterTextboxLeft.ForeColor = global::System.Drawing.Color.White;
			this.liceneCodeEnterTextboxLeft.Location = new global::System.Drawing.Point(1, 34);
			this.liceneCodeEnterTextboxLeft.Name = "liceneCodeEnterTextboxLeft";
			this.liceneCodeEnterTextboxLeft.Padding = new global::System.Windows.Forms.Padding(5);
			this.liceneCodeEnterTextboxLeft.Size = new global::System.Drawing.Size(4, 31);
			this.liceneCodeEnterTextboxLeft.TabIndex = 41;
			this.liceneCodeEnterTextboxLeft.Text = "Kalan süre: {0} gün, {0} saat, {0} dakika.";
			this.liceneCodeEnterTextboxLeft.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.licenseMessageLeft.BackColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.licenseMessageLeft.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.licenseMessageLeft.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.licenseMessageLeft.ForeColor = global::System.Drawing.Color.White;
			this.licenseMessageLeft.Location = new global::System.Drawing.Point(1, 71);
			this.licenseMessageLeft.Name = "licenseMessageLeft";
			this.licenseMessageLeft.Padding = new global::System.Windows.Forms.Padding(5);
			this.licenseMessageLeft.Size = new global::System.Drawing.Size(4, 24);
			this.licenseMessageLeft.TabIndex = 43;
			this.licenseMessageLeft.Text = "Kalan süre: {0} gün, {0} saat, {0} dakika.";
			this.licenseMessageLeft.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.licenseMessageLeft.Visible = false;
			this.licenseMessage.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.licenseMessage.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.licenseMessage.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.licenseMessage.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.licenseMessage.Location = new global::System.Drawing.Point(5, 71);
			this.licenseMessage.Name = "licenseMessage";
			this.licenseMessage.Padding = new global::System.Windows.Forms.Padding(5, 3, 5, 5);
			this.licenseMessage.Size = new global::System.Drawing.Size(352, 24);
			this.licenseMessage.TabIndex = 42;
			this.licenseMessage.Text = "Lisans mesaj varsayılan.";
			this.licenseMessage.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.licenseMessage.Visible = false;
			this.licenseCodeTextbox.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.licenseCodeTextbox.BorderStyle = global::System.Windows.Forms.BorderStyle.None;
			this.licenseCodeTextbox.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f);
			this.licenseCodeTextbox.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.licenseCodeTextbox.Location = new global::System.Drawing.Point(14, 41);
			this.licenseCodeTextbox.Name = "licenseCodeTextbox";
			this.licenseCodeTextbox.Size = new global::System.Drawing.Size(298, 17);
			this.licenseCodeTextbox.TabIndex = 44;
			this.hideLicenseMessageButton.AutoSize = true;
			this.hideLicenseMessageButton.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.hideLicenseMessageButton.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.hideLicenseMessageButton.Location = new global::System.Drawing.Point(338, 75);
			this.hideLicenseMessageButton.Name = "hideLicenseMessageButton";
			this.hideLicenseMessageButton.Size = new global::System.Drawing.Size(12, 13);
			this.hideLicenseMessageButton.TabIndex = 47;
			this.hideLicenseMessageButton.Text = "x";
			this.hideLicenseMessageButton.Visible = false;
			this.hideLicenseMessageButton.Click += new global::System.EventHandler(this.hideLicenseMessageButton_Click);
			this.licensePanel.Controls.Add(this.hideLicenseMessageButton);
			this.licensePanel.Controls.Add(this.licenseCodeEnterButton);
			this.licensePanel.Controls.Add(this.licenseCodeTextbox);
			this.licensePanel.Controls.Add(this.licenseMessage);
			this.licensePanel.Controls.Add(this.licenseMessageLeft);
			this.licensePanel.Controls.Add(this.liceneCodeEnterTextboxLeft);
			this.licensePanel.Controls.Add(this.premiumRemainingTime);
			this.licensePanel.Controls.Add(this.premiumRemainingTimeLeft);
			this.licensePanel.Controls.Add(this.premiumInfoLabel);
			this.licensePanel.Controls.Add(this.copyHBIDButton);
			this.licensePanel.Controls.Add(this.buyLicenseButton);
			this.licensePanel.Controls.Add(this.licenseCodeEnterLabel);
			this.licensePanel.Controls.Add(this.licenseCodeTextboxBackground);
			this.licensePanel.Location = new global::System.Drawing.Point(797, 166);
			this.licensePanel.Name = "licensePanel";
			this.licensePanel.Size = new global::System.Drawing.Size(359, 227);
			this.licensePanel.TabIndex = 105;
			this.licensePanel.Visible = false;
			this.licenseCodeEnterButton.BackColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.licenseCodeEnterButton.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.licenseCodeEnterButton.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11.25f);
			this.licenseCodeEnterButton.ForeColor = global::System.Drawing.Color.White;
			this.licenseCodeEnterButton.Image = global::linkapprove.Properties.Resources.tick_16;
			this.licenseCodeEnterButton.Location = new global::System.Drawing.Point(319, 34);
			this.licenseCodeEnterButton.Name = "licenseCodeEnterButton";
			this.licenseCodeEnterButton.Padding = new global::System.Windows.Forms.Padding(5);
			this.licenseCodeEnterButton.Size = new global::System.Drawing.Size(40, 31);
			this.licenseCodeEnterButton.TabIndex = 45;
			this.licenseCodeEnterButton.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.licenseCodeEnterButton.Click += new global::System.EventHandler(this.licenseCodeEnterButton_Click);
			this.licenseCodeTextboxBackground.BackColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.licenseCodeTextboxBackground.Location = new global::System.Drawing.Point(5, 34);
			this.licenseCodeTextboxBackground.Name = "licenseCodeTextboxBackground";
			this.licenseCodeTextboxBackground.Size = new global::System.Drawing.Size(315, 31);
			this.licenseCodeTextboxBackground.TabIndex = 46;
			this.licenseCodeTextboxBackground.TabStop = false;
			this.linkApproveYoPanel.Controls.Add(this.pictureBox1);
			this.linkApproveYoPanel.Controls.Add(this.tebriklerLabel);
			this.linkApproveYoPanel.Location = new global::System.Drawing.Point(428, 411);
			this.linkApproveYoPanel.Name = "linkApproveYoPanel";
			this.linkApproveYoPanel.Size = new global::System.Drawing.Size(359, 227);
			this.linkApproveYoPanel.TabIndex = 102;
			this.linkApproveYoPanel.Visible = false;
			this.pictureBox1.Image = global::linkapprove.Properties.Resources.yoyo;
			this.pictureBox1.Location = new global::System.Drawing.Point(97, 1);
			this.pictureBox1.Name = "pictureBox1";
			this.pictureBox1.Size = new global::System.Drawing.Size(162, 161);
			this.pictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.pictureBox1.TabIndex = 27;
			this.pictureBox1.TabStop = false;
			this.tebriklerLabel.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.tebriklerLabel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.tebriklerLabel.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.tebriklerLabel.Location = new global::System.Drawing.Point(1, 184);
			this.tebriklerLabel.Name = "tebriklerLabel";
			this.tebriklerLabel.Padding = new global::System.Windows.Forms.Padding(5);
			this.tebriklerLabel.Size = new global::System.Drawing.Size(357, 42);
			this.tebriklerLabel.TabIndex = 26;
			this.tebriklerLabel.Text = "Tebrikler, link onayı tamamlandı!";
			this.tebriklerLabel.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.languagePanel.Controls.Add(this.languageContentLabel);
			this.languagePanel.Controls.Add(this.languageLabel);
			this.languagePanel.Controls.Add(this.bayrak_lt);
			this.languagePanel.Controls.Add(this.bayrak_cz);
			this.languagePanel.Controls.Add(this.bayrak_de);
			this.languagePanel.Controls.Add(this.bayrak_hu);
			this.languagePanel.Controls.Add(this.bayrak_eg);
			this.languagePanel.Controls.Add(this.bayrak_fr);
			this.languagePanel.Controls.Add(this.bayrak_es);
			this.languagePanel.Controls.Add(this.bayrak_ro);
			this.languagePanel.Controls.Add(this.bayrak_bg);
			this.languagePanel.Controls.Add(this.bayrak_br);
			this.languagePanel.Controls.Add(this.bayrak_pl);
			this.languagePanel.Controls.Add(this.bayrak_ru);
			this.languagePanel.Controls.Add(this.bayrak_tr);
			this.languagePanel.Controls.Add(this.bayrak_en);
			this.languagePanel.Location = new global::System.Drawing.Point(797, 410);
			this.languagePanel.Name = "languagePanel";
			this.languagePanel.Size = new global::System.Drawing.Size(359, 101);
			this.languagePanel.TabIndex = 102;
			this.languagePanel.Visible = false;
			this.languageContentLabel.BackColor = global::System.Drawing.Color.FromArgb(230, 230, 233);
			this.languageContentLabel.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.languageContentLabel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.languageContentLabel.ForeColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.languageContentLabel.Location = new global::System.Drawing.Point(161, 2);
			this.languageContentLabel.Name = "languageContentLabel";
			this.languageContentLabel.Padding = new global::System.Windows.Forms.Padding(5);
			this.languageContentLabel.Size = new global::System.Drawing.Size(148, 28);
			this.languageContentLabel.TabIndex = 61;
			this.languageContentLabel.Text = "English";
			this.languageContentLabel.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.languageLabel.BackColor = global::System.Drawing.Color.FromArgb(47, 53, 66);
			this.languageLabel.Cursor = global::System.Windows.Forms.Cursors.Default;
			this.languageLabel.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 9.25f);
			this.languageLabel.ForeColor = global::System.Drawing.Color.FromArgb(244, 244, 246);
			this.languageLabel.Location = new global::System.Drawing.Point(47, 2);
			this.languageLabel.Name = "languageLabel";
			this.languageLabel.Padding = new global::System.Windows.Forms.Padding(5);
			this.languageLabel.Size = new global::System.Drawing.Size(110, 28);
			this.languageLabel.TabIndex = 60;
			this.languageLabel.Text = "Language:";
			this.languageLabel.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.bayrak_lt.BackColor = global::System.Drawing.Color.White;
			this.bayrak_lt.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_lt.Enabled = false;
			this.bayrak_lt.Image = global::linkapprove.Properties.Resources.flag_LT;
			this.bayrak_lt.Location = new global::System.Drawing.Point(275, 74);
			this.bayrak_lt.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_lt.Name = "bayrak_lt";
			this.bayrak_lt.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_lt.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_lt.TabIndex = 59;
			this.bayrak_lt.TabStop = false;
			this.bayrak_lt.Click += new global::System.EventHandler(this.bayrak_lt_Click);
			this.bayrak_lt.MouseEnter += new global::System.EventHandler(this.bayrak_lt_MouseEnter);
			this.bayrak_lt.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_cz.BackColor = global::System.Drawing.Color.White;
			this.bayrak_cz.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_cz.Enabled = false;
			this.bayrak_cz.Image = global::linkapprove.Properties.Resources.flag_CZ;
			this.bayrak_cz.Location = new global::System.Drawing.Point(237, 74);
			this.bayrak_cz.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_cz.Name = "bayrak_cz";
			this.bayrak_cz.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_cz.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_cz.TabIndex = 58;
			this.bayrak_cz.TabStop = false;
			this.bayrak_cz.Click += new global::System.EventHandler(this.bayrak_cz_Click);
			this.bayrak_cz.MouseEnter += new global::System.EventHandler(this.bayrak_cz_MouseEnter);
			this.bayrak_cz.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_de.BackColor = global::System.Drawing.Color.White;
			this.bayrak_de.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_de.Enabled = false;
			this.bayrak_de.Image = global::linkapprove.Properties.Resources.flag_DE;
			this.bayrak_de.Location = new global::System.Drawing.Point(161, 74);
			this.bayrak_de.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_de.Name = "bayrak_de";
			this.bayrak_de.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_de.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_de.TabIndex = 57;
			this.bayrak_de.TabStop = false;
			this.bayrak_de.Click += new global::System.EventHandler(this.bayrak_de_Click);
			this.bayrak_de.MouseEnter += new global::System.EventHandler(this.bayrak_de_MouseEnter);
			this.bayrak_de.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_hu.BackColor = global::System.Drawing.Color.White;
			this.bayrak_hu.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_hu.Enabled = false;
			this.bayrak_hu.Image = global::linkapprove.Properties.Resources.flag_HU;
			this.bayrak_hu.Location = new global::System.Drawing.Point(199, 74);
			this.bayrak_hu.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_hu.Name = "bayrak_hu";
			this.bayrak_hu.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_hu.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_hu.TabIndex = 56;
			this.bayrak_hu.TabStop = false;
			this.bayrak_hu.Click += new global::System.EventHandler(this.bayrak_hu_Click);
			this.bayrak_hu.MouseEnter += new global::System.EventHandler(this.bayrak_hu_MouseEnter);
			this.bayrak_hu.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_eg.BackColor = global::System.Drawing.Color.White;
			this.bayrak_eg.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_eg.Image = global::linkapprove.Properties.Resources.flag_EG;
			this.bayrak_eg.Location = new global::System.Drawing.Point(199, 45);
			this.bayrak_eg.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_eg.Name = "bayrak_eg";
			this.bayrak_eg.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_eg.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_eg.TabIndex = 55;
			this.bayrak_eg.TabStop = false;
			this.bayrak_eg.Click += new global::System.EventHandler(this.bayrak_eg_Click);
			this.bayrak_eg.MouseEnter += new global::System.EventHandler(this.bayrak_eg_MouseEnter);
			this.bayrak_eg.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_fr.BackColor = global::System.Drawing.Color.White;
			this.bayrak_fr.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_fr.Image = global::linkapprove.Properties.Resources.flag_FR;
			this.bayrak_fr.Location = new global::System.Drawing.Point(237, 45);
			this.bayrak_fr.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_fr.Name = "bayrak_fr";
			this.bayrak_fr.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_fr.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_fr.TabIndex = 54;
			this.bayrak_fr.TabStop = false;
			this.bayrak_fr.Click += new global::System.EventHandler(this.bayrak_fr_Click);
			this.bayrak_fr.MouseEnter += new global::System.EventHandler(this.bayrak_fr_MouseEnter);
			this.bayrak_fr.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_es.BackColor = global::System.Drawing.Color.White;
			this.bayrak_es.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_es.Enabled = false;
			this.bayrak_es.Image = global::linkapprove.Properties.Resources.flag_ES;
			this.bayrak_es.Location = new global::System.Drawing.Point(161, 45);
			this.bayrak_es.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_es.Name = "bayrak_es";
			this.bayrak_es.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_es.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_es.TabIndex = 53;
			this.bayrak_es.TabStop = false;
			this.bayrak_es.Click += new global::System.EventHandler(this.bayrak_es_Click);
			this.bayrak_es.MouseEnter += new global::System.EventHandler(this.bayrak_es_MouseEnter);
			this.bayrak_es.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_ro.BackColor = global::System.Drawing.Color.White;
			this.bayrak_ro.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_ro.Image = global::linkapprove.Properties.Resources.flag_RO;
			this.bayrak_ro.Location = new global::System.Drawing.Point(275, 45);
			this.bayrak_ro.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_ro.Name = "bayrak_ro";
			this.bayrak_ro.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_ro.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_ro.TabIndex = 52;
			this.bayrak_ro.TabStop = false;
			this.bayrak_ro.Click += new global::System.EventHandler(this.bayrak_ro_Click);
			this.bayrak_ro.MouseEnter += new global::System.EventHandler(this.bayrak_ro_MouseEnter);
			this.bayrak_ro.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_bg.BackColor = global::System.Drawing.Color.White;
			this.bayrak_bg.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_bg.Image = global::linkapprove.Properties.Resources.flag_BG;
			this.bayrak_bg.Location = new global::System.Drawing.Point(85, 74);
			this.bayrak_bg.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_bg.Name = "bayrak_bg";
			this.bayrak_bg.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_bg.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_bg.TabIndex = 51;
			this.bayrak_bg.TabStop = false;
			this.bayrak_bg.Click += new global::System.EventHandler(this.bayrak_bg_Click);
			this.bayrak_bg.MouseEnter += new global::System.EventHandler(this.bayrak_bg_MouseEnter);
			this.bayrak_bg.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_br.BackColor = global::System.Drawing.Color.White;
			this.bayrak_br.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_br.Image = global::linkapprove.Properties.Resources.flag_BR;
			this.bayrak_br.Location = new global::System.Drawing.Point(123, 45);
			this.bayrak_br.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_br.Name = "bayrak_br";
			this.bayrak_br.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_br.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_br.TabIndex = 50;
			this.bayrak_br.TabStop = false;
			this.bayrak_br.Click += new global::System.EventHandler(this.bayrak_br_Click);
			this.bayrak_br.MouseEnter += new global::System.EventHandler(this.bayrak_br_MouseEnter);
			this.bayrak_br.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_pl.BackColor = global::System.Drawing.Color.White;
			this.bayrak_pl.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_pl.Image = global::linkapprove.Properties.Resources.flag_PL;
			this.bayrak_pl.Location = new global::System.Drawing.Point(123, 74);
			this.bayrak_pl.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_pl.Name = "bayrak_pl";
			this.bayrak_pl.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_pl.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_pl.TabIndex = 49;
			this.bayrak_pl.TabStop = false;
			this.bayrak_pl.Click += new global::System.EventHandler(this.bayrak_pl_Click);
			this.bayrak_pl.MouseEnter += new global::System.EventHandler(this.bayrak_pl_MouseEnter);
			this.bayrak_pl.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_ru.BackColor = global::System.Drawing.Color.White;
			this.bayrak_ru.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_ru.Image = global::linkapprove.Properties.Resources.flag_RU;
			this.bayrak_ru.Location = new global::System.Drawing.Point(47, 74);
			this.bayrak_ru.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_ru.Name = "bayrak_ru";
			this.bayrak_ru.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_ru.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_ru.TabIndex = 48;
			this.bayrak_ru.TabStop = false;
			this.bayrak_ru.Click += new global::System.EventHandler(this.bayrak_ru_Click);
			this.bayrak_ru.MouseEnter += new global::System.EventHandler(this.bayrak_ru_MouseEnter);
			this.bayrak_ru.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_tr.BackColor = global::System.Drawing.Color.White;
			this.bayrak_tr.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_tr.Image = global::linkapprove.Properties.Resources.flag_TR;
			this.bayrak_tr.Location = new global::System.Drawing.Point(85, 45);
			this.bayrak_tr.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_tr.Name = "bayrak_tr";
			this.bayrak_tr.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_tr.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_tr.TabIndex = 47;
			this.bayrak_tr.TabStop = false;
			this.bayrak_tr.Click += new global::System.EventHandler(this.bayrak_tr_Click);
			this.bayrak_tr.MouseEnter += new global::System.EventHandler(this.bayrak_tr_MouseEnter);
			this.bayrak_tr.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.bayrak_en.BackColor = global::System.Drawing.Color.FromArgb(3, 91, 251);
			this.bayrak_en.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.bayrak_en.Image = global::linkapprove.Properties.Resources.flag_US;
			this.bayrak_en.Location = new global::System.Drawing.Point(47, 45);
			this.bayrak_en.MaximumSize = new global::System.Drawing.Size(34, 24);
			this.bayrak_en.Name = "bayrak_en";
			this.bayrak_en.Size = new global::System.Drawing.Size(34, 24);
			this.bayrak_en.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.bayrak_en.TabIndex = 46;
			this.bayrak_en.TabStop = false;
			this.bayrak_en.Click += new global::System.EventHandler(this.bayrak_en_Click);
			this.bayrak_en.MouseEnter += new global::System.EventHandler(this.bayrak_en_MouseEnter);
			this.bayrak_en.MouseLeave += new global::System.EventHandler(this.bayraklar_MouseLeave);
			this.ImageCSBOL.BackColor = global::System.Drawing.Color.Transparent;
			this.ImageCSBOL.Image = global::linkapprove.Properties.Resources.bol_link_approve_logo;
			this.ImageCSBOL.Location = new global::System.Drawing.Point(45, 35);
			this.ImageCSBOL.Name = "ImageCSBOL";
			this.ImageCSBOL.Size = new global::System.Drawing.Size(359, 105);
			this.ImageCSBOL.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.ImageCSBOL.TabIndex = 91;
			this.ImageCSBOL.TabStop = false;
			this.ImageCSBOL.Click += new global::System.EventHandler(this.ImageCSBOL_Click);
			this.ImageLoading.BackColor = global::System.Drawing.Color.White;
			this.ImageLoading.Image = global::linkapprove.Properties.Resources.opening_owl;
			this.ImageLoading.ImeMode = global::System.Windows.Forms.ImeMode.NoControl;
			this.ImageLoading.Location = new global::System.Drawing.Point(45, 215);
			this.ImageLoading.Name = "ImageLoading";
			this.ImageLoading.Size = new global::System.Drawing.Size(359, 205);
			this.ImageLoading.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.ImageLoading.TabIndex = 96;
			this.ImageLoading.TabStop = false;
			this.button1.Location = new global::System.Drawing.Point(355, 6);
			this.button1.Name = "button1";
			this.button1.Size = new global::System.Drawing.Size(73, 23);
			this.button1.TabIndex = 107;
			this.button1.Text = "eksikceviri";
			this.button1.UseVisualStyleBackColor = true;
			this.button1.Visible = false;
			this.button1.Click += new global::System.EventHandler(this.button1_Click);
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.White;
			base.ClientSize = new global::System.Drawing.Size(459, 561);
			base.Controls.Add(this.button1);
			base.Controls.Add(this.languagePanel);
			base.Controls.Add(this.linkApproveYoPanel);
			base.Controls.Add(this.panel3);
			base.Controls.Add(this.licensePanel);
			base.Controls.Add(this.altPanel);
			base.Controls.Add(this.ImageCSBOL);
			base.Controls.Add(this.linkApprovePanel);
			base.Controls.Add(this.ImageLoading);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "SecondForm";
			base.StartPosition = global::System.Windows.Forms.FormStartPosition.CenterScreen;
			this.Text = "BOL LINK APPROVE";
			base.FormClosed += new global::System.Windows.Forms.FormClosedEventHandler(this.Form3_FormClosed);
			base.Load += new global::System.EventHandler(this.Form3_Load);
			this.linkApprovePanel.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon12).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon9).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon6).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon3).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon11).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon8).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon5).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon10).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon7).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon4).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.linkIcon1).EndInit();
			this.altPanel.ResumeLayout(false);
			this.altPanel.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.webHilebol).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.socialInstagram).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.socialYoutube).EndInit();
			this.panel3.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.menuLanguage).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.menuLicense).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.menuLink).EndInit();
			this.licensePanel.ResumeLayout(false);
			this.licensePanel.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.licenseCodeTextboxBackground).EndInit();
			this.linkApproveYoPanel.ResumeLayout(false);
			this.linkApproveYoPanel.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pictureBox1).EndInit();
			this.languagePanel.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_lt).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_cz).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_de).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_hu).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_eg).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_fr).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_es).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_ro).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_bg).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_br).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_pl).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_ru).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_tr).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.bayrak_en).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.ImageCSBOL).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.ImageLoading).EndInit();
			base.ResumeLayout(false);
			base.PerformLayout();
		}
	}
}
