namespace Approve
{
	public partial class Form2 : global::System.Windows.Forms.Form
	{
		private global::System.ComponentModel.IContainer components;
		internal global::System.Windows.Forms.Panel PanelAlt;
		internal global::System.Windows.Forms.PictureBox PictureBox2;
		internal global::System.Windows.Forms.Label YoutubeText;
		internal global::System.Windows.Forms.ComboBox LanguagesCombobox;
		internal global::System.Windows.Forms.PictureBox buyPremiumImage;
		internal global::System.Windows.Forms.PictureBox LanguagesImage;
		internal global::System.Windows.Forms.Label buyPremiumText;
		internal global::System.Windows.Forms.PictureBox YoutubeImage;
		internal global::System.Windows.Forms.Panel PanelOnaylar;
		internal global::System.Windows.Forms.PictureBox Step1Image;
		internal global::System.Windows.Forms.Label Step1Text;
		internal global::System.Windows.Forms.PictureBox Step2Image;
		internal global::System.Windows.Forms.Label Step2Text;
		internal global::System.Windows.Forms.PictureBox Step3Image;
		internal global::System.Windows.Forms.Label Step3Text;
		internal global::System.Windows.Forms.PictureBox Step5Image;
		internal global::System.Windows.Forms.Label Step5Text;
		internal global::System.Windows.Forms.PictureBox Step6Image;
		internal global::System.Windows.Forms.Label Step1AltText;
		internal global::System.Windows.Forms.Label Step6Text;
		internal global::System.Windows.Forms.PictureBox Step4Image;
		internal global::System.Windows.Forms.Label Step4Text;
		private global::System.Windows.Forms.Timer step1;
		private global::System.Windows.Forms.Timer step2;
		private global::System.Windows.Forms.Timer step3;
		private global::System.Windows.Forms.Timer step4;
		private global::System.Windows.Forms.Timer step5;
		private global::System.Windows.Forms.Timer step6;
		internal global::System.Windows.Forms.Panel PanelOnayFinish;
		internal global::System.Windows.Forms.Label noktanokta;
		internal global::System.Windows.Forms.Label programdanCikiliyor;
		internal global::System.Windows.Forms.Label tumOnaylariTamamladin;
		internal global::System.Windows.Forms.PictureBox onayFinishImage;
		internal global::System.Windows.Forms.PictureBox LoadingImage;
		internal global::System.Windows.Forms.Panel PanelOnayBasarili;
		internal global::System.Windows.Forms.Label programYenidenBaslatiliyor;
		internal global::System.Windows.Forms.Label yapilmasiGerekenXonayKaldi;
		internal global::System.Windows.Forms.Label onayBasarili;
		internal global::System.Windows.Forms.PictureBox countdownGif;
		private global::System.Windows.Forms.Timer exiting;
		private global::System.Windows.Forms.Timer restart;
		private global::System.Windows.Forms.Timer load;
		internal global::System.Windows.Forms.Label iCantSeeAdText;
		internal global::System.Windows.Forms.PictureBox pictureBox1;
		
		protected override void Dispose(bool disposing)
		{
			if (disposing && this.components != null)
			{
				this.components.Dispose();
			}
			base.Dispose(disposing);
		}
		private void InitializeComponent()
		{
			this.components = new global::System.ComponentModel.Container();
			global::System.ComponentModel.ComponentResourceManager componentResourceManager = new global::System.ComponentModel.ComponentResourceManager(typeof(global::Approve.Form2));
			this.PanelAlt = new global::System.Windows.Forms.Panel();
			this.pictureBox1 = new global::System.Windows.Forms.PictureBox();
			this.iCantSeeAdText = new global::System.Windows.Forms.Label();
			this.PictureBox2 = new global::System.Windows.Forms.PictureBox();
			this.YoutubeText = new global::System.Windows.Forms.Label();
			this.LanguagesCombobox = new global::System.Windows.Forms.ComboBox();
			this.buyPremiumImage = new global::System.Windows.Forms.PictureBox();
			this.LanguagesImage = new global::System.Windows.Forms.PictureBox();
			this.buyPremiumText = new global::System.Windows.Forms.Label();
			this.YoutubeImage = new global::System.Windows.Forms.PictureBox();
			this.PanelOnaylar = new global::System.Windows.Forms.Panel();
			this.Step1Image = new global::System.Windows.Forms.PictureBox();
			this.Step1Text = new global::System.Windows.Forms.Label();
			this.Step2Image = new global::System.Windows.Forms.PictureBox();
			this.Step2Text = new global::System.Windows.Forms.Label();
			this.Step3Image = new global::System.Windows.Forms.PictureBox();
			this.Step3Text = new global::System.Windows.Forms.Label();
			this.Step5Image = new global::System.Windows.Forms.PictureBox();
			this.Step5Text = new global::System.Windows.Forms.Label();
			this.Step6Image = new global::System.Windows.Forms.PictureBox();
			this.Step1AltText = new global::System.Windows.Forms.Label();
			this.Step6Text = new global::System.Windows.Forms.Label();
			this.Step4Image = new global::System.Windows.Forms.PictureBox();
			this.Step4Text = new global::System.Windows.Forms.Label();
			this.step1 = new global::System.Windows.Forms.Timer(this.components);
			this.step2 = new global::System.Windows.Forms.Timer(this.components);
			this.step3 = new global::System.Windows.Forms.Timer(this.components);
			this.step4 = new global::System.Windows.Forms.Timer(this.components);
			this.step5 = new global::System.Windows.Forms.Timer(this.components);
			this.step6 = new global::System.Windows.Forms.Timer(this.components);
			this.PanelOnayFinish = new global::System.Windows.Forms.Panel();
			this.noktanokta = new global::System.Windows.Forms.Label();
			this.programdanCikiliyor = new global::System.Windows.Forms.Label();
			this.tumOnaylariTamamladin = new global::System.Windows.Forms.Label();
			this.onayFinishImage = new global::System.Windows.Forms.PictureBox();
			this.PanelOnayBasarili = new global::System.Windows.Forms.Panel();
			this.programYenidenBaslatiliyor = new global::System.Windows.Forms.Label();
			this.yapilmasiGerekenXonayKaldi = new global::System.Windows.Forms.Label();
			this.onayBasarili = new global::System.Windows.Forms.Label();
			this.countdownGif = new global::System.Windows.Forms.PictureBox();
			this.exiting = new global::System.Windows.Forms.Timer(this.components);
			this.restart = new global::System.Windows.Forms.Timer(this.components);
			this.load = new global::System.Windows.Forms.Timer(this.components);
			this.LoadingImage = new global::System.Windows.Forms.PictureBox();
			this.PanelAlt.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pictureBox1).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.buyPremiumImage).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.LanguagesImage).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.YoutubeImage).BeginInit();
			this.PanelOnaylar.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Step1Image).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step2Image).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step3Image).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step5Image).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step6Image).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step4Image).BeginInit();
			this.PanelOnayFinish.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.onayFinishImage).BeginInit();
			this.PanelOnayBasarili.SuspendLayout();
			((global::System.ComponentModel.ISupportInitialize)this.countdownGif).BeginInit();
			((global::System.ComponentModel.ISupportInitialize)this.LoadingImage).BeginInit();
			base.SuspendLayout();
			this.PanelAlt.Controls.Add(this.pictureBox1);
			this.PanelAlt.Controls.Add(this.iCantSeeAdText);
			this.PanelAlt.Controls.Add(this.PictureBox2);
			this.PanelAlt.Controls.Add(this.YoutubeText);
			this.PanelAlt.Controls.Add(this.LanguagesCombobox);
			this.PanelAlt.Controls.Add(this.buyPremiumImage);
			this.PanelAlt.Controls.Add(this.LanguagesImage);
			this.PanelAlt.Controls.Add(this.buyPremiumText);
			this.PanelAlt.Controls.Add(this.YoutubeImage);
			this.PanelAlt.Location = new global::System.Drawing.Point(17, 270);
			this.PanelAlt.Name = "PanelAlt";
			this.PanelAlt.Size = new global::System.Drawing.Size(331, 90);
			this.PanelAlt.TabIndex = 46;
			this.pictureBox1.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.pictureBox1.Image = global::Approve.Properties.Resources.i_cant_see_ad;
			this.pictureBox1.Location = new global::System.Drawing.Point(0, 63);
			this.pictureBox1.Name = "pictureBox1";
			this.pictureBox1.Size = new global::System.Drawing.Size(16, 16);
			this.pictureBox1.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.pictureBox1.TabIndex = 44;
			this.pictureBox1.TabStop = false;
			this.iCantSeeAdText.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.iCantSeeAdText.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f);
			this.iCantSeeAdText.ForeColor = global::System.Drawing.Color.Black;
			this.iCantSeeAdText.Location = new global::System.Drawing.Point(21, 65);
			this.iCantSeeAdText.Name = "iCantSeeAdText";
			this.iCantSeeAdText.Size = new global::System.Drawing.Size(200, 13);
			this.iCantSeeAdText.TabIndex = 43;
			this.iCantSeeAdText.Text = "I can't see ad!";
			this.iCantSeeAdText.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.iCantSeeAdText.Click += new global::System.EventHandler(this.iCantSeeAdText_Click);
			this.PictureBox2.BackColor = global::System.Drawing.Color.Gainsboro;
			this.PictureBox2.Location = new global::System.Drawing.Point(5, 1);
			this.PictureBox2.Name = "PictureBox2";
			this.PictureBox2.Size = new global::System.Drawing.Size(321, 1);
			this.PictureBox2.TabIndex = 37;
			this.PictureBox2.TabStop = false;
			this.YoutubeText.AutoSize = true;
			this.YoutubeText.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.YoutubeText.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f);
			this.YoutubeText.ForeColor = global::System.Drawing.Color.FromArgb(201, 2, 50);
			this.YoutubeText.Location = new global::System.Drawing.Point(21, 16);
			this.YoutubeText.Name = "YoutubeText";
			this.YoutubeText.Size = new global::System.Drawing.Size(130, 13);
			this.YoutubeText.TabIndex = 15;
			this.YoutubeText.Text = "Reklam onayı nasıl yapılır?";
			this.YoutubeText.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.YoutubeText.Click += new global::System.EventHandler(this.YoutubeText_Click);
			this.LanguagesCombobox.FlatStyle = global::System.Windows.Forms.FlatStyle.Flat;
			this.LanguagesCombobox.FormattingEnabled = true;
			this.LanguagesCombobox.ItemHeight = 13;
			this.LanguagesCombobox.Items.AddRange(new object[]
			{
				"Türkçe",
				"English",
				"Français",
				"Deutsch",
				"Español",
				"Português",
				"Român",
				"русский",
				"العربية",
				"български",
				"Polski",
				"Magyar",
				"Čeština"
			});
			this.LanguagesCombobox.Location = new global::System.Drawing.Point(249, 61);
			this.LanguagesCombobox.Name = "LanguagesCombobox";
			this.LanguagesCombobox.Size = new global::System.Drawing.Size(79, 21);
			this.LanguagesCombobox.TabIndex = 26;
			this.LanguagesCombobox.Text = "Language";
			this.LanguagesCombobox.SelectedIndexChanged += new global::System.EventHandler(this._11231817761);
			this.buyPremiumImage.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.buyPremiumImage.Image = global::Approve.Properties.Resources.dia;
			this.buyPremiumImage.Location = new global::System.Drawing.Point(0, 38);
			this.buyPremiumImage.Name = "buyPremiumImage";
			this.buyPremiumImage.Size = new global::System.Drawing.Size(16, 16);
			this.buyPremiumImage.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.buyPremiumImage.TabIndex = 42;
			this.buyPremiumImage.TabStop = false;
			this.LanguagesImage.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.LanguagesImage.Image = global::Approve.Properties.Resources.translate_16;
			this.LanguagesImage.Location = new global::System.Drawing.Point(225, 63);
			this.LanguagesImage.Name = "LanguagesImage";
			this.LanguagesImage.Size = new global::System.Drawing.Size(16, 16);
			this.LanguagesImage.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.LanguagesImage.TabIndex = 27;
			this.LanguagesImage.TabStop = false;
			this.buyPremiumText.AutoSize = true;
			this.buyPremiumText.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.buyPremiumText.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8.25f);
			this.buyPremiumText.ForeColor = global::System.Drawing.Color.FromArgb(0, 80, 192);
			this.buyPremiumText.Location = new global::System.Drawing.Point(21, 40);
			this.buyPremiumText.Name = "buyPremiumText";
			this.buyPremiumText.Size = new global::System.Drawing.Size(181, 13);
			this.buyPremiumText.TabIndex = 41;
			this.buyPremiumText.Text = "Buy premium for skip the Ad Approve";
			this.buyPremiumText.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.buyPremiumText.Click += new global::System.EventHandler(this.buyPremiumText_Click);
			this.YoutubeImage.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.YoutubeImage.Image = global::Approve.Properties.Resources.yt_mini;
			this.YoutubeImage.Location = new global::System.Drawing.Point(0, 16);
			this.YoutubeImage.Name = "YoutubeImage";
			this.YoutubeImage.Size = new global::System.Drawing.Size(18, 13);
			this.YoutubeImage.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.YoutubeImage.TabIndex = 34;
			this.YoutubeImage.TabStop = false;
			this.PanelOnaylar.BackColor = global::System.Drawing.Color.White;
			this.PanelOnaylar.Controls.Add(this.Step1Image);
			this.PanelOnaylar.Controls.Add(this.Step1Text);
			this.PanelOnaylar.Controls.Add(this.Step2Image);
			this.PanelOnaylar.Controls.Add(this.Step2Text);
			this.PanelOnaylar.Controls.Add(this.Step3Image);
			this.PanelOnaylar.Controls.Add(this.Step3Text);
			this.PanelOnaylar.Controls.Add(this.Step5Image);
			this.PanelOnaylar.Controls.Add(this.Step5Text);
			this.PanelOnaylar.Controls.Add(this.Step6Image);
			this.PanelOnaylar.Controls.Add(this.Step1AltText);
			this.PanelOnaylar.Controls.Add(this.Step6Text);
			this.PanelOnaylar.Controls.Add(this.Step4Image);
			this.PanelOnaylar.Controls.Add(this.Step4Text);
			this.PanelOnaylar.Location = new global::System.Drawing.Point(17, 12);
			this.PanelOnaylar.Name = "PanelOnaylar";
			this.PanelOnaylar.Size = new global::System.Drawing.Size(331, 251);
			this.PanelOnaylar.TabIndex = 45;
			this.Step1Image.Image = global::Approve.Properties.Resources.now;
			this.Step1Image.Location = new global::System.Drawing.Point(0, 3);
			this.Step1Image.Name = "Step1Image";
			this.Step1Image.Size = new global::System.Drawing.Size(34, 32);
			this.Step1Image.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.Step1Image.TabIndex = 4;
			this.Step1Image.TabStop = false;
			this.Step1Image.Click += new global::System.EventHandler(this.Step1Text_Click);
			this.Step1Text.AutoSize = true;
			this.Step1Text.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Step1Text.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.Step1Text.Location = new global::System.Drawing.Point(38, 1);
			this.Step1Text.Name = "Step1Text";
			this.Step1Text.Size = new global::System.Drawing.Size(218, 18);
			this.Step1Text.TabIndex = 5;
			this.Step1Text.Text = "Google'da \"{0}\" aramasını yapın.";
			this.Step1Text.Click += new global::System.EventHandler(this.Step1Text_Click);
			this.Step2Image.Image = global::Approve.Properties.Resources.waiting;
			this.Step2Image.Location = new global::System.Drawing.Point(0, 45);
			this.Step2Image.Name = "Step2Image";
			this.Step2Image.Size = new global::System.Drawing.Size(32, 32);
			this.Step2Image.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.Step2Image.TabIndex = 6;
			this.Step2Image.TabStop = false;
			this.Step2Text.AutoSize = true;
			this.Step2Text.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.Step2Text.Location = new global::System.Drawing.Point(38, 51);
			this.Step2Text.Name = "Step2Text";
			this.Step2Text.Size = new global::System.Drawing.Size(196, 18);
			this.Step2Text.TabIndex = 7;
			this.Step2Text.Text = "Google üzerinden {0}'a gidin.";
			this.Step3Image.Image = global::Approve.Properties.Resources.waiting;
			this.Step3Image.Location = new global::System.Drawing.Point(0, 87);
			this.Step3Image.Name = "Step3Image";
			this.Step3Image.Size = new global::System.Drawing.Size(32, 32);
			this.Step3Image.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.Step3Image.TabIndex = 8;
			this.Step3Image.TabStop = false;
			this.Step3Text.AutoSize = true;
			this.Step3Text.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.Step3Text.Location = new global::System.Drawing.Point(38, 93);
			this.Step3Text.Name = "Step3Text";
			this.Step3Text.Size = new global::System.Drawing.Size(183, 18);
			this.Step3Text.TabIndex = 9;
			this.Step3Text.Text = "Rastgele bir sayfaya geçin.";
			this.Step5Image.Image = global::Approve.Properties.Resources.waiting;
			this.Step5Image.Location = new global::System.Drawing.Point(0, 171);
			this.Step5Image.Name = "Step5Image";
			this.Step5Image.Size = new global::System.Drawing.Size(32, 32);
			this.Step5Image.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.Step5Image.TabIndex = 10;
			this.Step5Image.TabStop = false;
			this.Step5Text.AutoSize = true;
			this.Step5Text.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.Step5Text.Location = new global::System.Drawing.Point(38, 177);
			this.Step5Text.Name = "Step5Text";
			this.Step5Text.Size = new global::System.Drawing.Size(119, 18);
			this.Step5Text.TabIndex = 11;
			this.Step5Text.Text = "Reklama tıklayın.";
			this.Step6Image.Image = global::Approve.Properties.Resources.waiting;
			this.Step6Image.Location = new global::System.Drawing.Point(0, 213);
			this.Step6Image.Name = "Step6Image";
			this.Step6Image.Size = new global::System.Drawing.Size(32, 32);
			this.Step6Image.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.Step6Image.TabIndex = 12;
			this.Step6Image.TabStop = false;
			this.Step1AltText.AutoSize = true;
			this.Step1AltText.Cursor = global::System.Windows.Forms.Cursors.Hand;
			this.Step1AltText.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 8f);
			this.Step1AltText.Location = new global::System.Drawing.Point(40, 21);
			this.Step1AltText.Name = "Step1AltText";
			this.Step1AltText.Size = new global::System.Drawing.Size(174, 13);
			this.Step1AltText.TabIndex = 24;
			this.Step1AltText.Text = "aramayı gerçekleştirmek için tıklayın";
			this.Step1AltText.Click += new global::System.EventHandler(this.Step1Text_Click);
			this.Step6Text.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.Step6Text.Location = new global::System.Drawing.Point(38, 211);
			this.Step6Text.Name = "Step6Text";
			this.Step6Text.Size = new global::System.Drawing.Size(260, 36);
			this.Step6Text.TabIndex = 13;
			this.Step6Text.Text = "Reklam sayfasında {0} saniye bekleyin.";
			this.Step6Text.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.Step4Image.Image = global::Approve.Properties.Resources.waiting;
			this.Step4Image.Location = new global::System.Drawing.Point(0, 129);
			this.Step4Image.Name = "Step4Image";
			this.Step4Image.Size = new global::System.Drawing.Size(32, 32);
			this.Step4Image.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.AutoSize;
			this.Step4Image.TabIndex = 29;
			this.Step4Image.TabStop = false;
			this.Step4Text.Font = new global::System.Drawing.Font("Microsoft Sans Serif", 11f);
			this.Step4Text.Location = new global::System.Drawing.Point(38, 127);
			this.Step4Text.Name = "Step4Text";
			this.Step4Text.Size = new global::System.Drawing.Size(289, 36);
			this.Step4Text.TabIndex = 30;
			this.Step4Text.Text = "Açılan sayfada {0} saniye bekleyin.";
			this.Step4Text.TextAlign = global::System.Drawing.ContentAlignment.MiddleLeft;
			this.step1.Interval = 1;
			this.step1.Tick += new global::System.EventHandler(this._879251995499849692464221342858365);
			this.step2.Interval = 1;
			this.step2.Tick += new global::System.EventHandler(this._3751923226638);
			this.step3.Interval = 1;
			this.step3.Tick += new global::System.EventHandler(this._37133769819246235556841);
			this.step4.Interval = 1000;
			this.step4.Tick += new global::System.EventHandler(this._2114723566562137869918);
			this.step5.Interval = 1;
			this.step5.Tick += new global::System.EventHandler(this._917254351164975799485);
			this.step6.Interval = 1000;
			this.step6.Tick += new global::System.EventHandler(this._49349546732);
			this.PanelOnayFinish.BackColor = global::System.Drawing.Color.White;
			this.PanelOnayFinish.Controls.Add(this.noktanokta);
			this.PanelOnayFinish.Controls.Add(this.programdanCikiliyor);
			this.PanelOnayFinish.Controls.Add(this.tumOnaylariTamamladin);
			this.PanelOnayFinish.Controls.Add(this.onayFinishImage);
			this.PanelOnayFinish.Location = new global::System.Drawing.Point(745, 52);
			this.PanelOnayFinish.Name = "PanelOnayFinish";
			this.PanelOnayFinish.Size = new global::System.Drawing.Size(331, 168);
			this.PanelOnayFinish.TabIndex = 49;
			this.PanelOnayFinish.Visible = false;
			this.noktanokta.Font = new global::System.Drawing.Font("Microsoft YaHei", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.noktanokta.ForeColor = global::System.Drawing.Color.Black;
			this.noktanokta.Location = new global::System.Drawing.Point(1, 134);
			this.noktanokta.Name = "noktanokta";
			this.noktanokta.Size = new global::System.Drawing.Size(328, 19);
			this.noktanokta.TabIndex = 41;
			this.noktanokta.Text = "•••••";
			this.noktanokta.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.programdanCikiliyor.Font = new global::System.Drawing.Font("Microsoft YaHei", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.programdanCikiliyor.ForeColor = global::System.Drawing.Color.Black;
			this.programdanCikiliyor.Location = new global::System.Drawing.Point(1, 114);
			this.programdanCikiliyor.Name = "programdanCikiliyor";
			this.programdanCikiliyor.Size = new global::System.Drawing.Size(328, 20);
			this.programdanCikiliyor.TabIndex = 40;
			this.programdanCikiliyor.Text = "programdan çıkılıyor";
			this.programdanCikiliyor.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.tumOnaylariTamamladin.Font = new global::System.Drawing.Font("Microsoft YaHei", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 162);
			this.tumOnaylariTamamladin.ForeColor = global::System.Drawing.Color.FromArgb(2, 102, 252);
			this.tumOnaylariTamamladin.Location = new global::System.Drawing.Point(1, 92);
			this.tumOnaylariTamamladin.Name = "tumOnaylariTamamladin";
			this.tumOnaylariTamamladin.Size = new global::System.Drawing.Size(328, 22);
			this.tumOnaylariTamamladin.TabIndex = 39;
			this.tumOnaylariTamamladin.Text = "Tüm onayları tamamladın!";
			this.tumOnaylariTamamladin.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.onayFinishImage.Image = global::Approve.Properties.Resources.finish;
			this.onayFinishImage.Location = new global::System.Drawing.Point(0, 15);
			this.onayFinishImage.Name = "onayFinishImage";
			this.onayFinishImage.Size = new global::System.Drawing.Size(331, 70);
			this.onayFinishImage.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.onayFinishImage.TabIndex = 38;
			this.onayFinishImage.TabStop = false;
			this.PanelOnayBasarili.BackColor = global::System.Drawing.Color.White;
			this.PanelOnayBasarili.Controls.Add(this.programYenidenBaslatiliyor);
			this.PanelOnayBasarili.Controls.Add(this.yapilmasiGerekenXonayKaldi);
			this.PanelOnayBasarili.Controls.Add(this.onayBasarili);
			this.PanelOnayBasarili.Controls.Add(this.countdownGif);
			this.PanelOnayBasarili.Location = new global::System.Drawing.Point(382, 52);
			this.PanelOnayBasarili.Name = "PanelOnayBasarili";
			this.PanelOnayBasarili.Size = new global::System.Drawing.Size(331, 168);
			this.PanelOnayBasarili.TabIndex = 48;
			this.PanelOnayBasarili.Visible = false;
			this.programYenidenBaslatiliyor.Font = new global::System.Drawing.Font("Microsoft YaHei", 9.75f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.programYenidenBaslatiliyor.ForeColor = global::System.Drawing.Color.Black;
			this.programYenidenBaslatiliyor.Location = new global::System.Drawing.Point(1, 134);
			this.programYenidenBaslatiliyor.Name = "programYenidenBaslatiliyor";
			this.programYenidenBaslatiliyor.Size = new global::System.Drawing.Size(328, 19);
			this.programYenidenBaslatiliyor.TabIndex = 41;
			this.programYenidenBaslatiliyor.Text = "program yeniden başlatılıyor";
			this.programYenidenBaslatiliyor.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.yapilmasiGerekenXonayKaldi.Font = new global::System.Drawing.Font("Microsoft YaHei", 11.25f, global::System.Drawing.FontStyle.Regular, global::System.Drawing.GraphicsUnit.Point, 162);
			this.yapilmasiGerekenXonayKaldi.ForeColor = global::System.Drawing.Color.Black;
			this.yapilmasiGerekenXonayKaldi.Location = new global::System.Drawing.Point(1, 114);
			this.yapilmasiGerekenXonayKaldi.Name = "yapilmasiGerekenXonayKaldi";
			this.yapilmasiGerekenXonayKaldi.Size = new global::System.Drawing.Size(328, 20);
			this.yapilmasiGerekenXonayKaldi.TabIndex = 40;
			this.yapilmasiGerekenXonayKaldi.Text = "Yapılması gereken {0} onay kaldı.";
			this.yapilmasiGerekenXonayKaldi.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.onayBasarili.Font = new global::System.Drawing.Font("Microsoft YaHei", 12f, global::System.Drawing.FontStyle.Bold, global::System.Drawing.GraphicsUnit.Point, 162);
			this.onayBasarili.ForeColor = global::System.Drawing.Color.FromArgb(2, 102, 252);
			this.onayBasarili.Location = new global::System.Drawing.Point(1, 92);
			this.onayBasarili.Name = "onayBasarili";
			this.onayBasarili.Size = new global::System.Drawing.Size(328, 22);
			this.onayBasarili.TabIndex = 39;
			this.onayBasarili.Text = "Onay başarılı!";
			this.onayBasarili.TextAlign = global::System.Drawing.ContentAlignment.MiddleCenter;
			this.countdownGif.Image = global::Approve.Properties.Resources.countdown;
			this.countdownGif.Location = new global::System.Drawing.Point(0, 15);
			this.countdownGif.Name = "countdownGif";
			this.countdownGif.Size = new global::System.Drawing.Size(331, 70);
			this.countdownGif.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.countdownGif.TabIndex = 38;
			this.countdownGif.TabStop = false;
			this.exiting.Interval = 800;
			this.exiting.Tick += new global::System.EventHandler(this.exiting_Tick);
			this.restart.Interval = 8000;
			this.restart.Tick += new global::System.EventHandler(this.restart_Tick);
			this.load.Interval = 1;
			this.load.Tick += new global::System.EventHandler(this.load_Tick);
			this.LoadingImage.Image = global::Approve.Properties.Resources.loading;
			this.LoadingImage.Location = new global::System.Drawing.Point(382, 271);
			this.LoadingImage.Name = "LoadingImage";
			this.LoadingImage.Size = new global::System.Drawing.Size(331, 251);
			this.LoadingImage.SizeMode = global::System.Windows.Forms.PictureBoxSizeMode.CenterImage;
			this.LoadingImage.TabIndex = 47;
			this.LoadingImage.TabStop = false;
			base.AutoScaleDimensions = new global::System.Drawing.SizeF(6f, 13f);
			base.AutoScaleMode = global::System.Windows.Forms.AutoScaleMode.Font;
			this.BackColor = global::System.Drawing.Color.White;
			base.ClientSize = new global::System.Drawing.Size(365, 365);
			base.Controls.Add(this.PanelOnayFinish);
			base.Controls.Add(this.LoadingImage);
			base.Controls.Add(this.PanelOnayBasarili);
			base.Controls.Add(this.PanelAlt);
			base.Controls.Add(this.PanelOnaylar);
			base.FormBorderStyle = global::System.Windows.Forms.FormBorderStyle.FixedSingle;
			base.Icon = (global::System.Drawing.Icon)componentResourceManager.GetObject("$this.Icon");
			base.Name = "Form2";
			base.ShowIcon = false;
			this.Text = "Hile Bol - Ad Approve";
			base.TopMost = true;
			base.FormClosed += new global::System.Windows.Forms.FormClosedEventHandler(this.Form2_FormClosed);
			base.Load += new global::System.EventHandler(this._466834198884668499628);
			this.PanelAlt.ResumeLayout(false);
			this.PanelAlt.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.pictureBox1).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.PictureBox2).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.buyPremiumImage).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.LanguagesImage).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.YoutubeImage).EndInit();
			this.PanelOnaylar.ResumeLayout(false);
			this.PanelOnaylar.PerformLayout();
			((global::System.ComponentModel.ISupportInitialize)this.Step1Image).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step2Image).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step3Image).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step5Image).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step6Image).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.Step4Image).EndInit();
			this.PanelOnayFinish.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.onayFinishImage).EndInit();
			this.PanelOnayBasarili.ResumeLayout(false);
			((global::System.ComponentModel.ISupportInitialize)this.countdownGif).EndInit();
			((global::System.ComponentModel.ISupportInitialize)this.LoadingImage).EndInit();
			base.ResumeLayout(false);
		}
	}
}
